name: run-unit-test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: checkout prebuilt binary
      run: ./script/checkout_prebuilt_binary_for_ci.sh ${{ secrets.RAFI_PREBUILT_BINARY_USER }} ${{ secrets.RAFI_PREBUILT_BINARY_ACCESS_TOKEN }}
    # Workaround for a bug of GitHub Actions
    #   - https://github.com/actions/virtual-environments/issues/83
    #   - https://github.com/actions/virtual-environments/issues/110
    - name: install-boost
      run: >
        sudo apt-get install -y libboost-filesystem1.65.1 libboost-program-options1.65.1 libboost1.65-dev
        && sudo ln -s /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.65.1 /usr/lib/x86_64-linux-gnu/libboost_filesystem.so
        && sudo ln -s /usr/lib/x86_64-linux-gnu/libboost_program_options.so.1.65.1 /usr/lib/x86_64-linux-gnu/libboost_program_options.so
    - name: build_gtest
      run: ./script/build_gtest.sh
    - name: build_release
      run: ./script/build_release.sh
    - name: run_unit_test
      run: ./script/run_unit_test.sh Release
    - name: run_riscv_tests
      run: ./script/run_riscv_tests.sh
    - name: run_linux
      run: ./script/run_linux.sh
